### ISSUE TITLE
[bug]: error: failed to run custom build command for `tdlib-rs

### ISSUE THREAD

**Issue by denegny** [FedericoBruzzone/tgt#41]
### Describe the bug

error: failed to run custom build command for `tdlib-rs v1.0.5`

### Reproduction steps

1.git clone
2.cargo build --release --features download-tdlib

### Expected behavior

  error: failed to run custom build command for `tdlib-rs v1.0.5`

### Method of Installation

Cargo

### tgt version

version = "1.0.0"

### Operating System (including version and architecture)

LMDE 6

**Comment by FedericoBruzzone** [comment]
Thank you for your report.

Can you show me the error you come up with?

We also maintain `tdlib-rs` I think I can help you!😊

**Comment by denegny** [comment]
> Thank you for your report.
> 
> Can you show me the error you come up with?
> 
> We also maintain `tdlib-rs` I think I can help you!😊

```
   Compiling clap v4.5.15
error: failed to run custom build command for `tdlib-rs v1.0.5`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installUzw9pD/release/build/tdlib-rs-e7a0cdaf4c9fdae0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tdlib-rs-1.0.5/build.rs:163:40:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `tdlib-rs v1.0.5`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installUzw9pD/release/build/tdlib-rs-e7a0cdaf4c9fdae0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tdlib-rs-1.0.5/build.rs:163:40:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `tgt v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installUzw9pD`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by FedericoBruzzone** [comment]
Ok it is related to this #40.

I need more information, can you do what I ask in the last comment in the other issue?

**Comment by FedericoBruzzone** [comment]
Related also to #45
