### ISSUE TITLE
[bug]: cargo install tgt error MacOS on MBP M3 Pro

### ISSUE THREAD

**Issue by noizo** [FedericoBruzzone/tgt#45]
### Describe the bug

Can't install on Macbook M3 Pro

### Reproduction steps

1. cargo install tgt
```
error: failed to run custom build command for `tdlib-rs v1.0.5`

Caused by:
  process didn't exit successfully: `/var/folders/r2/1766py551tbf_vx2vmzzvyym0000gn/T/cargo-installn8qBvP/release/build/tdlib-rs-2d89c3480c06bac0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /Users/noizo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tdlib-rs-1.0.5/build.rs:163:40:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `tdlib-rs v1.0.5`

Caused by:
  process didn't exit successfully: `/var/folders/r2/1766py551tbf_vx2vmzzvyym0000gn/T/cargo-installn8qBvP/release/build/tdlib-rs-2d89c3480c06bac0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /Users/noizo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tdlib-rs-1.0.5/build.rs:163:40:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `tgt v1.0.0`, intermediate artifacts can be found at `/var/folders/r2/1766py551tbf_vx2vmzzvyym0000gn/T/cargo-installn8qBvP`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

### Expected behavior

Can install tgt

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

MacOS 14.6.1 (23G93)

### Terminal and Command Line Interface (CLI) (including versions)

kitty/zsh

### rustc and rustup target (including versions)

aarch64-apple-darwin

**Comment by FedericoBruzzone** [comment]
Related to #41

**Comment by FedericoBruzzone** [comment]
Related also to #40

**Comment by FedericoBruzzone** [comment]
The error message you're encountering while trying to compile a Rust project suggests that the build process failed due to a reqwest::Error which is related to an HTTP request that timed out. This seems to be happening in the build script of the tdlib-rs crate, which is causing the entire build process to fail.

`reqwest::Error { kind: Decode, source: TimedOut }`: indicates that a network request made during the build process took too long and eventually timed out.

Show me the output of
```bash
export RUST_BACKTRACE=1
cargo install tgt
```

**Comment by noizo** [comment]
Usual thing: on second run it worked fine :)

**Comment by FedericoBruzzone** [comment]
Perfect, thank you so much for the feedback! <3
