### ISSUE TITLE
[bug]: Random crashes when switching between windows

### ISSUE THREAD

**Issue by Kasaneru** [FedericoBruzzone/tgt#83]
### Describe the bug

Switching between chat list, chat and prompt causes random crashes.

### Reproduction steps

1. `cargo run --release`
2. Start switching focus between chat list, chat and prompt, switching chats or typing in prompt box.
3.  Error: `insertion index (is 1) should be <= len (is 0)`

### Expected behavior

Avoid crashes.

### Logs and screenshots
```
thread 'main' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:1576:13:
insertion index (is 1) should be <= len (is 0)
stack backtrace:
   0:     0x593915cb32f9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x593915bddd7b - core::fmt::write::hf5713710ce10ff22
   2:     0x593915c7dbd2 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x593915cb4a68 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x593915cb46e4 - std::panicking::default_hook::h81c8cd2e7c59ee33
   5:     0x593915b7f155 - tgt::init_panic_hook::{{closure}}::h7c1765d5326026fc
   6:     0x593915cb5699 - std::panicking::rust_panic_with_hook::had2118629c312a4a
   7:     0x593915cb5405 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   8:     0x593915cb5369 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   9:     0x593915cb5354 - rust_begin_unwind
  10:     0x593915ad0d52 - core::panicking::panic_fmt::h3eea515d05f7a35e
  11:     0x593915acf0e6 - alloc::vec::Vec<T,A>::insert::assert_failed::h4c36e5a582bf3fd3
  12:     0x593915b42471 - tgt::components::prompt_window::Input::insert::hd9fb5a70fcec0f70
  13:     0x593915b4331e - <tgt::components::prompt_window::PromptWindow as tgt::components::component_traits::Component>::update::hac3517bc34ee976d
  14:     0x593915b41e9c - <tgt::components::core_window::CoreWindow as tgt::components::component_traits::Component>::update::h5720991073d409c8
  15:     0x593915b6213c - tgt::run::handle_app_actions::{{closure}}::hdf40128e78bfaea9
  16:     0x593915b5925b - tgt::run::run_app::{{closure}}::h05b2fa373b244d7f
  17:     0x593915b7bc9b - tgt::tokio_main::{{closure}}::hc2ae0d9cfc2e2878
  18:     0x593915b840de - tgt::main::{{closure}}::hde6721008da5493b
  19:     0x593915b829bc - tgt::main::hd2e70249cf8e336f
  20:     0x593915ae4530 - std::sys::backtrace::__rust_begin_short_backtrace::h7b20a0c102ec9bff
  21:     0x593915ae43f0 - std::rt::lang_start::{{closure}}::hb742dff24e1834bf
  22:     0x593915b84700 - main
  23:     0x7a7948745e08 - <unknown>
  24:     0x7a7948745ecc - __libc_start_main
  25:     0x593915adbab5 - _start
  26:                0x0 - <unknown>
```

### Method of Installation

Build from source

### tgt version

1.0.0

### Operating System (including version and architecture)

Linux x86_64

### rustc and rustup target (including versions)

rustc 1.82.0 (f6e511eec 2024-10-15)

**Comment by Andreal2000** [comment]
Hi, thanks for opening this issue.

Can you send us the output of the crash but with the app runned with the `--verbose` option enabled ?

**Comment by Kasaneru** [comment]
`--release --verbose` used, full output:

```
       Fresh unicode-ident v1.0.12
       Fresh autocfg v1.3.0
       Fresh version_check v0.9.4
       Fresh pkg-config v0.3.30
       Fresh once_cell v1.19.0
       Fresh proc-macro2 v1.0.86
       Fresh cfg-if v1.0.0
       Fresh vcpkg v0.2.15
       Fresh quote v1.0.36
       Fresh libc v0.2.155
       Fresh zerocopy v0.7.34
       Fresh allocator-api2 v0.2.18
       Fresh memchr v2.7.4
       Fresh scopeguard v1.2.0
       Fresh syn v2.0.85
       Fresh jobserver v0.1.31
       Fresh ahash v0.8.11
       Fresh pin-project-lite v0.2.14
       Fresh cc v1.0.103
       Fresh serde_derive v1.0.213
       Fresh thiserror-impl v1.0.63
       Fresh lock_api v0.4.12
       Fresh openssl-macros v0.1.1
       Fresh pin-project-internal v1.1.5
       Fresh itoa v1.0.11
       Fresh futures-core v0.3.31
       Fresh parking_lot_core v0.9.10
       Fresh num-traits v0.2.19
       Fresh signal-hook-registry v1.4.2
       Fresh hashbrown v0.14.5
       Fresh equivalent v1.0.1
       Fresh mio v1.0.1
       Fresh parking_lot v0.12.3
       Fresh indexmap v2.2.6
       Fresh crossbeam-utils v0.8.20
       Fresh log v0.4.22
       Fresh futures-sink v0.3.31
       Fresh bytes v1.6.0
       Fresh typenum v1.17.0
       Fresh thiserror v1.0.63
       Fresh either v1.13.0
       Fresh linux-raw-sys v0.4.14
       Fresh bitflags v2.6.0
       Fresh fnv v1.0.7
       Fresh serde v1.0.213
       Fresh rustix v0.38.34
       Fresh slab v0.4.9
       Fresh generic-array v0.14.7
       Fresh zeroize_derive v1.4.2
       Fresh tracing-core v0.1.32
       Fresh smallvec v1.13.2
       Fresh crossbeam-epoch v0.9.18
       Fresh futures-channel v0.3.31
       Fresh tracing-attributes v0.1.27
       Fresh futures-macro v0.3.31
       Fresh tokio-macros v2.4.0
       Fresh socket2 v0.5.7
       Fresh futures-io v0.3.31
       Fresh minimal-lexical v0.2.1
       Fresh ident_case v1.0.1
       Fresh adler v1.0.2
       Fresh pin-utils v0.1.0
       Fresh futures-task v0.3.31
       Fresh nom v7.1.3
       Fresh miniz_oxide v0.7.4
       Fresh darling_core v0.20.9
       Fresh futures-util v0.3.31
       Fresh tracing v0.1.40
       Fresh tokio v1.41.0
       Fresh crossbeam-deque v0.8.5
       Fresh displaydoc v0.2.5
       Fresh crc32fast v1.4.2
       Fresh ryu v1.0.18
       Fresh simd-adler32 v0.3.7
       Fresh rayon-core v1.12.1
       Fresh darling_macro v0.20.9
       Fresh crypto-common v0.1.6
       Fresh http v1.1.0
       Fresh itertools v0.12.1
       Fresh num-integer v0.1.46
       Fresh libloading v0.8.4
       Fresh tdlib-rs-parser v1.0.5
       Fresh tdlib-rs-gen v1.0.5
       Fresh dlib v0.5.2
       Fresh num-bigint v0.4.6
       Fresh darling v0.20.9
       Fresh paste v1.0.15
       Fresh rustversion v1.0.17
       Fresh crunchy v0.2.2
       Fresh flate2 v1.0.30
       Fresh aligned-vec v0.5.0
       Fresh arrayvec v0.7.4
       Fresh built v0.7.3
       Fresh heck v0.5.0
       Fresh foreign-types-shared v0.1.1
       Fresh num-rational v0.4.2
       Fresh tiny-keccak v2.0.2
       Fresh v_frame v0.3.8
       Fresh foreign-types v0.3.2
       Fresh wayland-sys v0.31.2
       Fresh anyhow v1.0.86
       Fresh serde_with_macros v3.8.1
       Fresh http-body v1.0.0
       Fresh rayon v1.10.0
       Fresh openssl-sys v0.9.103
       Fresh tokio-util v0.7.11
       Fresh block-buffer v0.10.4
       Fresh profiling-procmacros v1.0.15
       Fresh getrandom v0.2.15
       Fresh quick-xml v0.31.0
       Fresh bytemuck v1.16.1
       Fresh subtle v2.6.1
       Fresh atomic-waker v1.1.2
       Fresh try-lock v0.2.5
       Fresh tinyvec_macros v0.1.1
       Fresh downcast-rs v1.2.1
       Fresh scoped-tls v1.0.1
       Fresh rand_core v0.6.4
       Fresh h2 v0.4.5
       Fresh httparse v1.9.4
       Fresh openssl v0.10.66
       Fresh profiling v1.0.15
       Fresh wayland-scanner v0.31.2
       Fresh wayland-backend v0.3.4
       Fresh tinyvec v1.6.1
       Fresh want v0.3.1
       Fresh digest v0.10.7
       Fresh av1-grain v0.2.3
       Fresh maybe-rayon v0.1.1
       Fresh const-random-macro v0.1.16
       Fresh spin v0.9.8
       Fresh pin-project v1.1.5
       Fresh arg_enum_proc_macro v0.3.4
       Fresh num-derive v0.4.2
       Fresh simd_helpers v0.1.0
       Fresh powerfmt v0.2.0
       Fresh tower-service v0.3.2
       Fresh tower-layer v0.3.2
       Fresh noop_proc_macro v0.3.0
       Fresh weezl v0.1.8
       Fresh imgref v1.10.1
       Fresh ppv-lite86 v0.2.17
       Fresh new_debug_unreachable v1.0.6
       Fresh openssl-probe v0.1.5
       Fresh unicode-segmentation v1.11.0
       Fresh percent-encoding v2.3.1
       Fresh quick-error v2.0.1
       Fresh regex-syntax v0.8.4
       Fresh bitstream-io v2.4.2
       Fresh cfg_aliases v0.1.1
       Fresh regex-syntax v0.6.29
       Fresh loop9 v0.1.5
       Fresh deranged v0.3.11
       Fresh tower v0.4.13
       Fresh regex-automata v0.4.7
       Fresh regex-automata v0.1.10
       Fresh rav1e v0.7.1
       Fresh form_urlencoded v1.2.1
       Fresh native-tls v0.2.12
       Fresh rand_chacha v0.3.1
       Fresh unicode-normalization v0.1.23
       Fresh const-random v0.1.18
       Fresh hyper v1.3.1
       Fresh wayland-client v0.31.3
       Fresh flume v0.11.0
       Fresh pest_meta v2.7.10
       Fresh zstd-sys v2.0.11+zstd.1.5.6
       Fresh rgb v0.8.50
       Fresh avif-serialize v0.8.1
       Fresh strum_macros v0.26.4
       Fresh castaway v0.2.3
       Fresh inout v0.1.3
       Fresh zune-inflate v0.2.54
       Fresh fdeflate v0.3.4
       Fresh encoding_rs v0.8.34
       Fresh half v2.4.1
       Fresh unicode-bidi v0.3.15
       Fresh lazy_static v1.5.0
       Fresh iana-time-zone v0.1.60
       Fresh jpeg-decoder v0.3.1
       Fresh color_quant v1.1.0
       Fresh time-core v0.1.2
       Fresh num-conv v0.1.0
       Fresh bit_field v0.10.2
       Fresh zune-core v0.4.12
       Fresh byteorder-lite v0.1.0
       Fresh static_assertions v1.1.0
       Fresh cpufeatures v0.2.12
       Fresh lebe v0.5.2
       Fresh crc-catalog v2.4.0
       Fresh bitflags v1.3.2
       Fresh unicode-width v0.1.13
       Fresh utf8parse v0.2.2
       Fresh fixedbitset v0.4.2
       Fresh overload v0.1.1
       Fresh sharded-slab v0.1.7
       Fresh zune-jpeg v0.4.13
       Fresh exr v1.72.0
       Fresh crc v3.2.1
       Fresh image-webp v0.2.0
       Fresh compact_str v0.8.0
       Fresh png v0.17.13
       Fresh petgraph v0.6.5
       Fresh unicode-truncate v1.0.0
       Fresh anstyle-parse v0.2.4
       Fresh nu-ansi-term v0.46.0
       Fresh chrono v0.4.38
       Fresh tiff v0.9.1
       Fresh bzip2-sys v0.1.11+1.0.8
       Fresh idna v0.5.0
       Fresh time v0.3.36
       Fresh gif v0.13.1
       Fresh ravif v0.11.7
       Fresh pest_generator v2.7.10
       Fresh cipher v0.4.4
       Fresh wayland-protocols v0.31.2
       Fresh zstd-safe v7.1.0
       Fresh strum v0.26.3
       Fresh dlv-list v0.5.2
       Fresh tokio-native-tls v0.3.1
       Fresh regex v1.10.5
       Fresh hyper-util v0.1.5
       Fresh rand v0.8.5
       Fresh signal-hook v0.3.17
       Fresh matchers v0.1.0
       Fresh hmac v0.12.1
       Fresh qoi v0.4.1
       Fresh http-body-util v0.1.2
       Fresh tracing-log v0.2.0
       Fresh itertools v0.13.0
       Fresh toml_datetime v0.6.6
       Fresh serde_spanned v0.6.6
       Fresh lru v0.12.3
       Fresh instability v0.3.2
       Fresh thread_local v1.1.8
       Fresh fastrand v2.1.0
       Fresh byteorder v1.5.0
       Fresh home v0.5.9
       Fresh lockfree-object-pool v0.1.6
       Fresh colorchoice v1.0.1
       Fresh option-ext v0.2.0
       Fresh rustls-pki-types v1.7.0
       Fresh base64 v0.22.1
       Fresh anstyle-query v1.1.0
       Fresh anstyle v1.0.8
       Fresh bumpalo v3.16.0
       Fresh is_terminal_polyfill v1.70.0
       Fresh winnow v0.6.13
       Fresh ucd-trie v0.1.6
       Fresh base64 v0.21.7
       Fresh cassowary v0.3.0
       Fresh zopfli v0.8.1
       Fresh pest v2.7.10
       Fresh rustls-pemfile v2.1.2
       Fresh anstream v0.6.14
       Fresh toml_edit v0.22.14
       Fresh dirs-sys v0.4.1
       Fresh tempfile v3.10.1
       Fresh lzma-rs v0.3.0
       Fresh serde_json v1.0.119
       Fresh tracing-subscriber v0.3.18
       Fresh tree_magic_mini v3.1.5
       Fresh image v0.25.4
       Fresh nix v0.28.0
       Fresh ordered-multimap v0.7.3
       Fresh hyper-tls v0.6.0
       Fresh signal-hook-mio v0.2.4
       Fresh pbkdf2 v0.12.2
       Fresh pest_derive v2.7.10
       Fresh zstd v0.13.2
       Fresh aes v0.8.4
       Fresh url v2.5.2
       Fresh bzip2 v0.4.4
       Fresh wayland-protocols-wlr v0.2.0
       Fresh sha1 v0.10.6
       Fresh serde_urlencoded v0.7.1
       Fresh zeroize v1.8.1
       Fresh sync_wrapper v1.0.1
       Fresh hashlink v0.8.4
       Fresh derive-new v0.6.0
       Fresh os_pipe v1.2.0
       Fresh x11rb-protocol v0.13.1
       Fresh mime v0.3.17
       Fresh arraydeque v0.5.1
       Fresh deflate64 v0.1.9
       Fresh clap_lex v0.7.1
       Fresh constant_time_eq v0.3.0
       Fresh ipnet v2.9.0
       Fresh strsim v0.11.1
       Fresh x11rb v0.13.1
       Fresh wl-clipboard-rs v0.8.1
       Fresh yaml-rust2 v0.8.1
       Fresh rust-ini v0.20.0
       Fresh json5 v0.4.1
       Fresh crossterm v0.28.1
       Fresh ratatui v0.28.1
       Fresh reqwest v0.12.8
       Fresh zip v2.2.0
       Fresh clap_builder v4.5.20
       Fresh toml v0.8.14
       Fresh dirs v5.0.1
       Fresh ron v0.8.1
       Fresh convert_case v0.6.0
       Fresh serde_with v3.8.1
       Fresh clap_derive v4.5.18
       Fresh futures-executor v0.3.31
       Fresh crossbeam-channel v0.5.13
       Fresh async-trait v0.1.80
       Fresh unicode-width v0.2.0
       Fresh icy_sixel v0.1.2
       Fresh pathdiff v0.2.1
       Fresh indoc v2.0.5
       Fresh dyn-clone v1.0.17
       Fresh futures v0.3.31
       Fresh tdlib-rs v1.0.5
       Fresh clap v4.5.20
       Fresh arboard v3.4.1
       Fresh ratatui-image v2.0.1
       Fresh config v0.14.1
       Fresh ratatui v0.29.0
       Fresh tracing-appender v0.2.3
       Fresh tracing-error v0.2.0
       Fresh tgt v1.0.0 (/home/taida/Scripts/tgt)
    Finished `release` profile [optimized] target(s) in 0.22s
     Running `target/release/tgt`
[ 3][t 0][1730487800.437462091][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 2.000000
[ 3][t 4][1730487800.439097166][Td.cpp:2547][#1][!MultiTd]	Create Td with layer 179, database version 14 and version 53 on 4 threads
[ 3][t 4][1730487800.439280271][Td.cpp:4059][#1][!Td][&td_requests]	Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.8.29"
  }
}
[ 3][t 4][1730487800.439347028][Td.cpp:4059][#1][!Td][&td_requests]	Sending update: updateOption {
  name = "commit_hash"
  value = optionValueString {
    value = "af69dd4397b6dc1bf23ba0fd0bf429fcba6454f6"
  }
}
[ 3][t 4][1730487800.439383029][Td.cpp:4067][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
[ 3][t 0][1730487800.439378976][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x75fbdc001d60
[ 3][t 4][1730487800.439411163][Td.cpp:2942][#1][!Td][&td_requests]	Receive request 1: setLogVerbosityLevel {
  new_verbosity_level = 2
}
thread 'main' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:1576:13:
insertion index (is 1) should be <= len (is 0)
stack backtrace:
   0:     0x5dad0a5932f9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x5dad0a4bdd7b - core::fmt::write::hf5713710ce10ff22
   2:     0x5dad0a55dbd2 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x5dad0a594a68 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x5dad0a5946e4 - std::panicking::default_hook::h81c8cd2e7c59ee33
   5:     0x5dad0a45f155 - tgt::init_panic_hook::{{closure}}::h7c1765d5326026fc
   6:     0x5dad0a595699 - std::panicking::rust_panic_with_hook::had2118629c312a4a
   7:     0x5dad0a595405 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   8:     0x5dad0a595369 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   9:     0x5dad0a595354 - rust_begin_unwind
  10:     0x5dad0a3b0d52 - core::panicking::panic_fmt::h3eea515d05f7a35e
  11:     0x5dad0a3af0e6 - alloc::vec::Vec<T,A>::insert::assert_failed::h4c36e5a582bf3fd3
  12:     0x5dad0a422471 - tgt::components::prompt_window::Input::insert::hd9fb5a70fcec0f70
  13:     0x5dad0a42331e - <tgt::components::prompt_window::PromptWindow as tgt::components::component_traits::Component>::update::hac3517bc34ee976d
  14:     0x5dad0a421e9c - <tgt::components::core_window::CoreWindow as tgt::components::component_traits::Component>::update::h5720991073d409c8
  15:     0x5dad0a44213c - tgt::run::handle_app_actions::{{closure}}::hdf40128e78bfaea9
  16:     0x5dad0a43925b - tgt::run::run_app::{{closure}}::h05b2fa373b244d7f
  17:     0x5dad0a45bc9b - tgt::tokio_main::{{closure}}::hc2ae0d9cfc2e2878
  18:     0x5dad0a4640de - tgt::main::{{closure}}::hde6721008da5493b
  19:     0x5dad0a4629bc - tgt::main::hd2e70249cf8e336f
  20:     0x5dad0a3c4530 - std::sys::backtrace::__rust_begin_short_backtrace::h7b20a0c102ec9bff
  21:     0x5dad0a3c43f0 - std::rt::lang_start::{{closure}}::hb742dff24e1834bf
  22:     0x5dad0a464700 - main
  23:     0x75fc41434e08 - <unknown>
  24:     0x75fc41434ecc - __libc_start_main
  25:     0x5dad0a3bbab5 - _start
  26:                0x0 - <unknown>
```

**Comment by FedericoBruzzone** [comment]
It sounds very strange this error, can you tell me what terminal emulator you are using?

Also, have you tried different font sizes yet if it still happens?

**Comment by Kasaneru** [comment]
I found problem appearing using vim keymap (https://github.com/FedericoBruzzone/tgt/blob/main/docs/vim_keymap.toml).
Specifically in lines
```
  # Focus the chat list
  { keys = ["1"], command = "focus_chat_list", description = "Focus the chat list"},
  # Focus the chat
  { keys = ["2"], command = "focus_chat", description = "Focus the chat"},
  # Focus the prompt
  { keys = ["3"], command = "focus_prompt", description = "Focus the prompt"},
```
as switching directly between prompt and chat causes any further input into prompt crash the app. This doesn't happen if you deselect prompt using `esc` and then switching to chat. So `3, 2, 3` and `3, 2, esc, 3` crashes, but `3, esc, 2, ...` doesn't.
Also, using `alt+1`, `alt+2`, `alt+3` from original keymap solves the problem. Thinking about, vim keymap doesn't allow to input digits 1-3 so it's better just to edit it.

**Comment by FedericoBruzzone** [comment]
Thank you for the report.

So would it be better to use `alt-1` etc... to switch between windows in vim-mode as well?

**Comment by FedericoBruzzone** [comment]
Awesome!
If you want to contribute to `tgt` feel free to submit a PR with this small changes to the vim keybindings.
If you don't want to, just tell me I'll fix it no problem.
